# Generated by Django 3.2.12 on 2022-06-16 03:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('countries_plus', '0005_auto_20160224_1804'),
        ('users', '0002_auto_20220609_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('amount', models.DecimalField(decimal_places=7, default=0.0, max_digits=20)),
            ],
            options={
                'verbose_name': 'Crypto Currency',
                'verbose_name_plural': 'Crypto Currencies',
                'ordering': ['-created'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SmartsUpp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('script', models.TextField()),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Smartsupp Upload',
                'verbose_name_plural': 'Smartsupp Uploads',
                'ordering': ['-created'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='addresses',
            name='qr',
            field=stdimage.models.StdImageField(blank=True, upload_to='qr/'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='uuid',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='uuid',
            field=models.CharField(blank=True, max_length=35, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.ForeignKey(blank=True, default='US', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='countries_plus.country'),
        ),
        migrations.AddField(
            model_name='user',
            name='dp',
            field=stdimage.models.StdImageField(blank=True, upload_to='user/dp'),
        ),
        migrations.AddField(
            model_name='user',
            name='ref',
            field=models.CharField(blank=True, max_length=25, verbose_name='Referral Link'),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='uuid',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='users.currency'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit', to='users.currency'),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='users.currency'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdraw', to='users.currency'),
        ),
    ]
