# Generated by Django 3.2.12 on 2022-06-16 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220615_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ref',
            field=models.CharField(blank=True, max_length=120, verbose_name='Referral Link'),
        ),
    ]
