# Generated by Django 3.2.12 on 2022-06-17 12:38

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('comment', models.TextField()),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Testimonial Upload',
                'verbose_name_plural': 'Testimonial Uploads',
                'ordering': ['-created'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='wallet',
            name='usdt',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=20),
        ),
    ]
